### PR TITLE
backend: Fix unable to fetch through externalproxy

### PR DESCRIPTION
**Pull request by lijianzhi01**
There are few bugs in externalproxy: 
* proxy-to will be removed from header by browser fetch method
* devMode should add Forward-To to AllowedHeaders
* r.URL.Path should set to empty

### CODE REVIEW

**Comment by lijianzhi01** [comment]
* proxy-to will be removed from header by fetch
```
# run following code in browser console
const a = await fetch("http://localhost:4466/externalproxy", {
    headers: {
      'proxy-to': "http://google.com",
    },
});
```
You will see the proxy-to will be **removed** from request header.
image

**Comment by lijianzhi01** [comment]
* devMode should add Forward-To to AllowedHeaders
image

**Comment by lijianzhi01** [comment]
* r.URL.Path should set to empty
If r.URL.Path is not set to be empty. The proxy url will be modified.
```
const a = await fetch("http://localhost:4466/externalproxy", {
    headers: {
      'proxy-to': "http://google.com",
    },
});
```
image

**Comment by joaquimrocha** [comment]
@yolossn , can you take a look?

**Review by yolossn — CHANGES_REQUESTED** [review]
Thanks for the contribution. Left a suggestion.

**Comment by lijianzhi01** [comment]
Your suggestion makes code more robustic. Thanks @yolossn

**Review by yolossn — APPROVED** [review]

**Pull request merged**
