### PR TITLE
frontend: xterm missing allowProposedApi option added

### PR DESCRIPTION
**Pull request by veyselsahin**

### CODE REVIEW

**Comment by skoeva** [comment]
Thanks for this! When you are ready to mark this for review, please don't forget to sign off the commit (you can do this using `git commit -s` or for an existing commit, use `git commit -s --amend`)

**Comment by skoeva** [comment]
Solid, if you're done making changes then an atomic commit would be preferred (instructions [here](https://headlamp.dev/docs/latest/contributing/#2-follow-commit-guidelines)), and like before, sign it off using `git commit -s`

**Comment by skoeva** [comment]
Did you run into git-related issues? Let us know if you would like to continue working on this issue

**Comment by veyselsahin** [comment]
Hey @skoeva, please bear with me as I feel a bit rusty on git and the evolved contributing process:) I reset the head of the branch to deliver an atomic commit that hides my scratches. Here is the recently created PR after my reset https://github.com/headlamp-k8s/headlamp/pull/2562

**Pull request closed without merging**
