### PR TITLE
plugins: Fix copying to docker containers

### PR DESCRIPTION
**Pull request by knrt10**
We were copying plugins but we were not installing dependecies which resulted some example plugins to not get copied.

headlamp-events plugin was also using local dev dependency which resulted in failure of installing it. This fixes it.

Fixes: #1695

### CODE REVIEW

**Comment by knrt10** [comment]
> Can you please add a test to check if (some or at least one) plugin(s) are copied so it doesn't regress in the future? See recent PR for Dockerfile.

There is already an e2e tests, for it, but I will modify it to check exact plugins are there as we have in examples folder.

**Review by joaquimrocha — APPROVED** [review]
LGTM.

**Comment by joaquimrocha** [comment]
@knrt10 , the patch LGTM. Can you check if you can answer these questions by Rene:
```
It would be interesting to know why it didn't fail before? The headlamp-plugin build command should fail CI there if it fails itself. Or maybe another command was failing and continuing without error? That command failing should fail CI.

It looks like the build command isn't checking webpack for errors. https://github.com/headlamp-k8s/headlamp/blob/main/plugins/headlamp-plugin/bin/headlamp-plugin.js#L478 See the docs here for how it uses callbacks not throwing an exception to handle errors: https://webpack.js.org/api/node#webpack
```

**Comment by knrt10** [comment]
> It would be interesting to know why it didn't fail before? The headlamp-plugin build command should fail CI there if it fails itself. Or maybe another command was failing and continuing without error? That command failing should fail CI.

It didn't fail earlier because as you suggested we are not handling webpack callback errors, so due to which it marks the builds as successful. It should fail the CI, I am looking more into it.

> It looks like the build command isn't checking webpack for errors. https://github.com/headlamp-k8s/headlamp/blob/main/plugins/headlamp-plugin/bin/headlamp-plugin.js#L478 See the docs here for how it uses callbacks not throwing an exception to handle errors: https://webpack.js.org/api/node#webpack

Thank you, looking more into why webpack issues are there.

We should not merge it now because webpack errors are still there. I am trying to fix it.

**Review by joaquimrocha — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
