### PR TITLE
frontend: Cache font from google api for airgapped environment

### PR DESCRIPTION
**Pull request by lijianzhi01**
Cache font from google api for airgapped environment. This is not a complete, because it needs backend set response header with text/css.

### CODE REVIEW

**Comment by lijianzhi01** [comment]
I just code font style in index.html. It can save one request from browser.

**Comment by joaquimrocha** [comment]
@lijianzhi01 Does this really work in airgap? I see it still referencing the fonts from Google's servers in your changes.
I'd expect us to ship the fonts if we want them in an airgapped env.

**Comment by lijianzhi01** [comment]
> @lijianzhi01 Does this really work in airgap? I see it still referencing the fonts from Google's servers in your changes. I'd expect us to ship the fonts if we want them in an airgapped env.

You are right. I am not fully cache those fonts. I will cache fonts instead.

**Comment by lijianzhi01** [comment]
Hi @joaquimrocha, I have cached each kinds of fonts in public folder. 
image

**Review by illume — APPROVED** [review]
Looks fine to me. A good improvement, thanks!

I'll tweak a few things in another branch and merge.

**Pull request merged**
