### PR TITLE
Misc fixes to k8s classes to the ResourceClasses object and new tests

### PR DESCRIPTION
**Pull request by joaquimrocha**
This PR adds a few fixes to the k8s classes we have as ResourceClasses in Headlamp.
It also adds a new test to prevent related regressions. This new test checks whether certain classes 1. have the listRoute correctly set, 2. are namespaced or not; and 3. are being tested or not.

How to test:
- [ ] Create resources of the LimitRange, Lease, PriorityClass, and RuntimeClass (add the YAML to the creation dialog after pressing Create): verify that they can be created
- [ ] Run the k8s/index.test.ts test (make frontend-test)

### CODE REVIEW

**Comment by vyncent-t** [comment]
Tried with the following templates and then changing some fields but was unable to add it

image

image

**Comment by joaquimrocha** [comment]
@vyncent-t Good catch! It was indeed missing a commit, and in the meanwhile I added more tests and fixes. Thanks.
I have updated the description for extra checks.

**Comment by illume** [comment]
@vyncent-t can you please review this again?

**Comment by vyncent-t** [comment]
Just tried again with the templates from the screen shots and it works!

**Comment by illume** [comment]
Thanks @vyncent-t

**Pull request merged**
