### PR TITLE
backend: Update go helm chart dependencies and related packages

### PR DESCRIPTION
**Pull request by joaquimrocha**
This also fixes a requirement for the CodeQL tool (needing a toolchain version for the go.mod).

### CODE REVIEW

**Comment by illume** [comment]
I learnt about toolchains here: https://go.dev/doc/toolchain 

Are there any other resources explaining this issue?

**Comment by joaquimrocha** [comment]
> I learnt about go toolchains here: https://go.dev/doc/toolchain and https://go.dev/blog/rebuild
> 
> Are there any other resources explaining this issue?

I am not sure. I noticed this got added after I ran go mod tidy. Unrelatedly noticed that CodeQL was complaining that the toolchain was missing.

**Comment by illume** [comment]
I have go 1.22.1 locally at the moment. With this it downloads the 1.22.3 that I'm missing to do the build.

Pretty sweet!

> $ make backend
> cd backend && go build -o ./headlamp-server ./cmd
> go: downloading go1.22.3 (linux/amd64)
> go: downloading k8s.io/apimachinery v0.30.0
> go: downloading k8s.io/client-go v0.30.0

**Review by illume — APPROVED** [review]
👍 thanks

**Review by illume — APPROVED** [review]
:+1: thanks

**Review by knrt10 — APPROVED** [review]
Thank you for the PR

**Pull request merged**
