### PR TITLE
frontend: Resource/CreateButton: Add cluster selector

### PR DESCRIPTION
**Pull request by illume**
So users can select which cluster to apply the resource to.

Only shows the cluster selector if there is more than one
cluster being viewed.

For single cluster mode there is no change.

~~Note: depends on this being merged:~~
- ~~https://github.com/headlamp-k8s/headlamp/pull/2428~~

### CODE REVIEW

**Review by sniok — APPROVED** [review]

**Review by joaquimrocha — CHANGES_REQUESTED** [review]
I think the cluster selector makes sense to be in the extraActions you created the other PR for, right?
As it's more discoverable for the user? Also, for now we may keep it single cluster selection, but it's be pretty cool to be able to select either the full cluster group or multiple individual clusters, so we could batch applies. But this can be added later.

**Comment by illume** [comment]
> I think the cluster selector makes sense to be in the extraActions you created the other PR for, right?

Yeah [https://github.com/headlamp-k8s/headlamp/pull/2428/files#diff-bd17d08e06e757d92d123c96d6fe154071e41f2dd53bfd1a096743023d66e8d2R67
](in this "frontend: EditorDialog: Add optional actions property" PR), the `actions` prop was added which is used in this PR.

> As it's more discoverable for the user? Also, for now we may keep it single cluster selection, but it's be pretty cool to be able to select either the full cluster group or multiple individual clusters, so we could batch applies. But this can be added later.

Ok, I added a task here for that: https://github.com/headlamp-k8s/headlamp/issues/1699#issuecomment-2416239082

**Comment by illume** [comment]
(rebased against main now that the #2428 is merged)

**Comment by joaquimrocha** [comment]
I did misunderstand where the actions in this PR would end up. Clarified in DM. All good.

**Review by joaquimrocha — APPROVED** [review]

**Pull request merged**
