### PR TITLE
frontend: headlamp-plugin: Upgrade monaco-editor to 0.52.0

### PR DESCRIPTION
**Pull request by illume**
https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md
https://github.com/microsoft/monaco-editor/commits/main/webpack-plugin

### Testing done

- Edited a pod / smoke test editor

### CODE REVIEW

**Comment by knrt10** [comment]
There are some file conflicts. Can you please fix it?

**Comment by illume** [comment]
@knrt10 fixed.

**Review by sniok — APPROVED** [review]
tested, editor works 👍

**Review by knrt10 — APPROVED** [review]
+1. Thanks

**Pull request merged**
