### PR TITLE
frontend: Fix alignment for calendar Icon

### PR DESCRIPTION
**Pull request by vyncent-t**
## Description:
When navigating to a timestamp using the date and calendar option, there has been an alignment issue noticed. This fix ensures that the date and calendar display are properly aligned to enhance user readability and aesthetics.

## Changes:

- [x]  Adjusted CSS properties for date element to ensure proper alignment.

**Before**
image

**After**
image

### CODE REVIEW

**Comment by joaquimrocha** [comment]
Testing this again, I noticed that it brings the label to the left, whereas it was aligned to the right before these changes. And this slight difference makes that column look misaligned. So this issue needs to be fixed.

**Review by joaquimrocha — CHANGES_REQUESTED** [review]
The label needs to be aligned to right as before.

**Comment by egomezbpedro** [comment]
Hi, 
this is due the property flex expanding all the way to the left. We could use justifyContent/justifySelf: 'flex-end' to bring the label to the original position without changing the element width or retain the inline-block display and use verticalAlign: 'middle' on the icon.

**Comment by vyncent-t** [comment]
> Hi, this is due the property flex expanding all the way to the left. We could use justifyContent/justifySelf: 'flex-end' to bring the label to the original position without changing the element width or retain the inline-block display and use verticalAlign: 'middle' on the icon.

Thank you I applied fixes for this issue to properly align the label

**before**

image

**after**

image

**Review by joaquimrocha — APPROVED** [review]
Nice!

**Pull request merged**
