### PR TITLE
frontend: Load Monaco from node_module and export Monaco to plugin

### PR DESCRIPTION
**Pull request by lijianzhi01**
This PR covers two scenarios:

- Load Monaco Editor from node_module instead of cdn for airgaped environment.
image
image

- For those of who want to create monaco editor in plugin, they can leverage monaco editor exported from frontend. It can reduce the size of plugin. In our case, we create editor for manage data stored in annotation.

### CODE REVIEW

**Comment by illume** [comment]
Hi,

I made a patch so this works with `npm run test`. (also see draft PR https://github.com/headlamp-k8s/headlamp/pull/1038)

[0001-frontend-Fix-monaco-editor-imports-to-be-jest-friend.patch](https://github.com/headlamp-k8s/headlamp/files/11016727/0001-frontend-Fix-monaco-editor-imports-to-be-jest-friend.patch)

```bash
git apply 0001-frontend-Fix-monaco-editor-imports-to-be-jest-friend.patch
```

**Comment by lijianzhi01** [comment]
> Hi,
> 
> I made a patch so this works with `npm run test`. (also see testing PR #1038) with the changes in commit [3815e73](https://github.com/headlamp-k8s/headlamp/commit/3815e734b6450e6d4d30d8fc613eddda6d43e88c)
> 
> [0001-frontend-Fix-monaco-editor-imports-to-be-jest-friend.patch](https://github.com/headlamp-k8s/headlamp/files/11016727/0001-frontend-Fix-monaco-editor-imports-to-be-jest-friend.patch)
> 
> ```shell
> git apply 0001-frontend-Fix-monaco-editor-imports-to-be-jest-friend.patch
> ```

I have tried this patch. Editor does not show highlights anymore.
image

**Comment by illume** [comment]
Ah ok. See a new commit d5bc2c7b6364f3986c14594fb8728f05b2c47d54 It passes tests on PR https://github.com/headlamp-k8s/headlamp/pull/1057 and also works with syntax highlighting.

New patch file is attached: [0001-frontend-Fix-monaco-editor-imports-to-be-jest-friend.patch](https://github.com/headlamp-k8s/headlamp/files/11071013/0001-frontend-Fix-monaco-editor-imports-to-be-jest-friend.patch)

```
git apply 0001-frontend-Fix-monaco-editor-imports-to-be-jest-friend.patch
```

**Comment by lijianzhi01** [comment]
Cool, it worked.

**Review by illume — APPROVED** [review]
👍 thanks @lijianzhi01

**Pull request merged**
