### PR TITLE
app: Dependency updates

### PR DESCRIPTION
**Pull request by illume**
Remove and update some app/ dependencies.

- mkdirp 3.0.1, https://github.com/isaacs/node-mkdirp/blob/main/CHANGELOG.md
- tar 7.4.0, https://github.com/isaacs/node-tar/blob/main/CHANGELOG.md
- Remove unused @types/semver
- dotenv 16.0.1 to 16.4.5
- Add app/tsconfig.json to formatted file list
- jest 27.4.7 to 29.7.0
- Remove open dep, use builtin openExternal
- yargs 16.2.0 to 17.7.2
- i18next to 23.12.1 and i18next-fs-backend to 2.3.1
- i18next-parser 7.7.0 to 9.0.0
- Remove electron-log dependency
- electron-wix-msi 4.0.0 to 5.1.3, https://github.com/electron-userland/electron-wix-msi/blob/master/CHANGELOG.md
- @electron/notarize 2.1.0 to 2.3.2
- @babel/* deps
- typescript 4.5.5 to 5.5.3
- tsconfig: Bump target from "es6" to "2023"
- Remove regenerator-runtime dependency
- octokit 2.1.0 to 4.0.2
- app: winget-create: Remove node-fetch import
- plugins: plugin-management: Remove node-fetch import
- app: Add node and npm minimum requirements
- app: Fix babelrc to target node 20
- app: Add plugin-management and convert to ts

### Testing done

- [x] each commit builds on CI
- [x] ran the app, did some smoke testing
- [x] tested pushing assets using push-release-assets.js

### CODE REVIEW

**Comment by joaquimrocha** [comment]
@illume I have just tested push-release-assets.js:
1. Create a new version draft, call it e.g. v0.1234 (DO NOT PUBLISH)
2. Run the push-release-assets.js script with any file, like `node push-release-assets.js v0.123 somefile.zip`

Worked fine just by moving to this branch.

**Comment by illume** [comment]
Thanks @joaquimrocha

**Comment by illume** [comment]
Rebased against main, because merge conflict.

**Comment by illume** [comment]
The "Build Container" job failure is unrelated to this.

**Comment by illume** [comment]
Rebased against main to fix conflict.

**Comment by illume** [comment]
Fixed a lint issue.

**Review by joaquimrocha — APPROVED** [review]

**Pull request merged**
