### PR TITLE
docs: Fix typo in plugin READMEs

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by surajssd** [comment]
cc: @ashu8912 @joaquimrocha

**Review by joaquimrocha — CHANGES_REQUESTED** [review]
The hyphen bullets are needed for consistency where we have several lines (divided by `<br/>`).
I see that the newline rendering is broken in the website, but still would like to keep the bullets for when we have them fixed.

**Comment by surajssd** [comment]
@joaquimrocha PTAL.

**Review by joaquimrocha — APPROVED** [review]
LGTM. Thanks @surajssd .

**Pull request merged**
