### PR TITLE
app: Do not use rename to move plugin folders

### LINKED ISSUE #2259: Cannot install plugins on Flatpak
Installing plugins on flatpak is broken due to cross-device linking.

### PR DESCRIPTION
**Pull request by joaquimrocha**
Instead use copy+removal so it works across partitions.

fixes #2259

### CODE REVIEW

**Review by yolossn — CHANGES_REQUESTED** [review]
Lint is failing apart from that looks good, tested it.

**Comment by illume** [comment]
Ooops. @joaquimrocha Sorry I didn't mean to push up my change here. Please feel free to revert to your commit.

I added a throw err, because otherwise it would call the success callback when it's failed.

**Review by illume — APPROVED** [review]
👍

**Comment by illume** [comment]
(fossa didn't update the PR check)

**Pull request merged**
