### PR TITLE
frontend: get rid of most @mui/styles

### PR DESCRIPTION
**Pull request by farodin91**
prepare for react 18

### CODE REVIEW

**Comment by joaquimrocha** [comment]
Hi @farodin91 , can you run the snapshots on this branch and push again?

**Comment by farodin91** [comment]
Updated.

I have to checkout how make test more stable.

**Comment by joaquimrocha** [comment]
@farodin91 Looks like these changes end up with generated css class names that are unique and thus this will break tests, since each run will generate new names and thus not match the snapshots.

I am not sure there's a straight solution to address the unique name generation. I wonder if this is also needed for React 18, but maybe I missed the docs from MUI that indicate that.

**Comment by farodin91** [comment]
https://mui.com/system/styles/api/ here is deprecation notice.

**Comment by joaquimrocha** [comment]
@farodin91  Right. I see that they mention using `sx`. Perhaps this property is more snapshot friendly?

**Comment by farodin91** [comment]
I will test out one with sx.

**Comment by joaquimrocha** [comment]
@farodin91 I guess we should close this in favor of updating the styles using the `sx` way?

**Pull request closed without merging**
